[package]
name = "spc700"
version = "0.1.0"
edition = "2024"

[dependencies]
libm = "0.2.15"
log = "0.4.28"

[dev-dependencies]
criterion = "0.3"
cpal = "0.16.0"
fixed-resample = "0.9.2"

[[bench]]
name = "spcplay_benchmark"
harness = false
